spring:
  application:
    name: markable-dev-analytics
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devanalytics
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
git:
  repositories:
    - https://scm.x5.ru/gkr/xrg-core.git
    - https://scm.x5.ru/gkr/xrg-markable.git
    - https://scm.x5.ru/gkpl/logistics-service.git
    - https://scm.x5.ru/gkpl/pricing-service.git
    - https://scm.x5.ru/gkpl/platform-service.git
    - https://scm.x5.ru/gkpl/bo-oas.git
  token:
  cache-directory:
server:
  port: 8080