spring:
  application:
    name: markable-dev-analytics
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devanalytics
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 8080